### PR TITLE
Switching to 1 log file (0 is a magic number) and fixing invalid project file config

### PR DESCRIPTION
**Pull request by bhariharan**
0 doesn't prevent log rolling, it only prevents log archive deleting.

### CODE REVIEW

**Comment by bhariharan** [comment]
@sgoldberg-sfdc

**Comment by brandonpage** [comment]
## Current coverage for SalesforceAnalytics.framework is `61.67%`
Files changed | - | - 
--- | --- | ---
SFSDKLogFileManager.m | `94.12%` | :white_check_mark:

---

> Powered by [xcov](https://github.com/nakiostudio/xcov)

<p align="right" data-meta="generated_by_CI-result">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by sgoldberg-sfdc** [comment]
Confirmed the behavior around log file deletion. When set to 0 it bypasses deletion based on number of log files (it will still delete if total size surpasses disk quota). A value of 1 will delete archived files. 

Why the xcode compat version change?

**Comment by sgoldberg-sfdc** [comment]
Approved after merging my PR against your fork to fix the isLogFile method.

**Comment by bhariharan** [comment]
@sgoldberg-sfdc Merged your PR against my fork. As for the compatibility change, I'm fixing a `Find and Replace` fail from before.

**Pull request merged**
