### PR TITLE
- fix deadlock due to dispatch_once on [SFUserAccountManager init].

### PR DESCRIPTION
**Pull request by samipdesai**
https://rink.hockeyapp.net/manage/apps/71830/app_versions/1856/crashes/10746012307

### CODE REVIEW

**Comment by samipdesai** [comment]
@bhariharan @khawkins . i am seeing another deadlock see the hockeyApp link for reference.

**Comment by huminzhi** [comment]
build

**Comment by khawkins** [comment]
Not to say that we shouldn't find more graceful failure fallbacks than deadlocks to these situations, but the reason that they're coming up in your case is that `SalesforceSDKManager` is not being initialized/`launch`ed as the first access to the Mobile SDK, which is an anti-pattern.  The SDK manager launch process is meant to precede all other access to SDK components.

**Comment by samipdesai** [comment]
Thanks @khawkins! i just spoke with @sgoldberg-sfdc and I am currently investigating if it possible to change things on our side as well.

**Comment by huminzhi** [comment]
build

**Comment by khawkins** [comment]
I've got a WIP to remove `SalesforceSDKManager` from the responsibility chain of these feature settings.  Stay tuned.

**Comment by huminzhi** [comment]
build

**Comment by khawkins** [comment]
@samipdesai I think [#1949](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/1949) should alleviate the kinds of deadlocks you're seeing, when it's merged.

**Comment by samipdesai** [comment]
@khawkins thats a much better fix.  quick question. will this have any detrimental effects if i cherry pick the commits on to master for out team fork? We need to address this in an upcoming release.

**Comment by khawkins** [comment]
I wouldn't imagine, as it just reorganized the existing functionality into different ownership.

**Comment by huminzhi** [comment]
build

**Comment by samipdesai** [comment]
I will close this in favor of @khawkins PR.

**Pull request closed without merging**
