### PR TITLE
Adding deprecation warnings for old NetworkSDK

### PR DESCRIPTION
**Pull request by bhariharan**

### CODE REVIEW

**Comment by bhariharan** [comment]
@trooper2013 @khawkins @sgoldberg-sfdc What do you think?

**Comment by huminzhi** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          2 Errors
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Tests have failed, see below for more information.</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Code coverage under minimum of 80%</td>
    </tr>
  </tbody>
</table>

### Tests: 

Classname | Name|
--- | ---|
CSFMultipartInputStreamTests | testMixedObjectElements|
CSFMultipartInputStreamTests | testMixedObjectElements|
CSFMultipartInputStreamTests | testMixedObjectElements|
CSFMultipartInputStreamTests | testMixedObjectElements|
CSFMultipartInputStreamTests | testMixedObjectElements|
CSFMultipartInputStreamTests | testMultipleStringElements|
CSFMultipartInputStreamTests | testMultipleStringElements|
CSFMultipartInputStreamTests | testMultipleStringElements|
CSFMultipartInputStreamTests | testMultipleStringElements|
CSFMultipartInputStreamTests | testSingleStringElement|
CSFMultipartInputStreamTests | testSingleStringElement|


## Current coverage for SalesforceSDKCore.framework is `48%`
✅ *No files affecting coverage found*

---
## Current coverage for SalesforceAnalytics.framework is `41%`
✅ *No files affecting coverage found*

---

> Powered by [xcov](https://github.com/nakiostudio/xcov)

<p align="right" data-meta="generated_by_CI-result">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by khawkins** [comment]
We have a macro for this: `SFSDK_DEPRECATED()`

**Comment by bhariharan** [comment]
I guess I should've looked first 🤕

**Comment by bhariharan** [comment]
I'm closing this for now since it generates too many warnings in the workspace. I'll add this next release - gives us enough runway before `6.0`.

**Pull request closed without merging**
