### PR TITLE
Add Id and LastModifiedDate if they're missing

### PR DESCRIPTION
**Pull request by bhariharan**
Tests coming up.

### CODE REVIEW

**Comment by wmathurin** [comment]
Looks good.
Shouldn't there be more code simplifications in the sample app?
Could we have a little test?

**Comment by bhariharan** [comment]
Yes - adding test as we speak. Not much simplification in sample app other than we can afford to drop ```LastModifiedDate``` from the ```SOQL``` query for ```syncDown```.

**Comment by wmathurin** [comment]
What about the Id? Can't we drop that too from the SOQL query?

**Comment by wmathurin** [comment]
:+1:

**Comment by bhariharan** [comment]
Added test [here](https://github.com/bhariharan/SalesforceMobileSDK-iOS/commit/6e7cc7c256520f7a30648150db9b0fc927ecfe2c). I'll drop ```Id``` too.

**Pull request merged**
