### PR TITLE
SmartStore compilation on XCode 9

### PR DESCRIPTION
**Pull request by wmathurin**
Using sqlite3.h that comes with sqlcipher

### CODE REVIEW

**Comment by wmathurin** [comment]
I'm still looking at the cocoapods side of things.

**Comment by bhariharan** [comment]
Is it not bundled as part of the `podspec` for `SQLCipher`?

**Comment by wmathurin** [comment]
It is bundled. But FMDB is including from &lt;sqlite3.h&gt; and picks up the system one. If I change the include to "sqlite3.h" it works fine.
Trying to figure out the right xconfig setting in SmartStore.podspec to make it work.

**Comment by wmathurin** [comment]
Will address the cocoapod side with separate PRs.

**Pull request merged**
