### PR TITLE
Using fixed version of shells (generation of hybrid local failing wit…

### PR DESCRIPTION
**Pull request by wmathurin**
…h shelljs 0.6.0)

### CODE REVIEW

**Comment by khawkins** [comment]
:+1:

Depending on the extent of updates to support a new version of shelljs, I wouldn't be averse to losing it altogether, either.  It's not particularly necessary on the iOS (OS X) side, where it's simply mimicking built-in unix functionality.

**Comment by kchitalia** [comment]
:+1:

**Comment by wmathurin** [comment]
I haven't looked at it too closely. But shelljs.cp where we copy path/* is now failing, complaining that it can't find path/*. 

It's the second time in a couple of months (last one was the sqlcipher release of 3.3) that an update to a third party library we depend on cause some of our stuff to break.
In the future, I recommend, we pin down the exact version we need wherever we use third party libraries.

**Comment by bhariharan** [comment]
I agree with @khawkins. We could lose it on ```iOS``` and use straight up ```exec``` calls instead, since it's limited to ```OS X```. Usage of ```shelljs``` in ```forcedroid``` might be unavoidable though, in order to support ```Windows```.

**Comment by bhariharan** [comment]
:+1:

**Pull request merged**
