### PR TITLE
Don't fetch auth config for login pools

### PR DESCRIPTION
**Pull request by bbirman**

### CODE REVIEW

**Review by brandonpage — APPROVED** [review]
Nice.  This came up recently when looking at logs, people were concerned and questioning why we would get a 404 from this call.  This should cut down on some of the noise.

**Review by wmathurin — COMMENTED** [review]
Do we need the same on Android?

**Comment by brandonpage** [comment]
> Do we need the same on Android?

Android has done this for years.

**Review by wmathurin — APPROVED** [review]

**Comment by bbirman** [comment]
Investigating the test failures separately, one has started flapping before this and the other seems based on iOS version

**Pull request merged**
