### PR TITLE
We need the split up specs at the root of the repo to be able to do:

### PR DESCRIPTION
**Pull request by wmathurin**
pod 'SalesforceSDKCore', :path => 'some clone of the repo'
or
pod 'SalesforceSDKCore', :git => 'some git version of the repo'

### CODE REVIEW

**Comment by kchitalia** [comment]
:+1:

**Comment by bhariharan** [comment]
Shouldn't this go against ```master``` for ```4.0.1```?

**Comment by wmathurin** [comment]
We could cherry pick that in master.

**Comment by khawkins** [comment]
:+1:

**Comment by wmathurin** [comment]
It's not that useful in master - since master is (soon to be) released code.
It's very useful in unstable, to be able to try sample code against a local clone or some random branch etc.

**Pull request merged**
