### PR TITLE
fix unit test on travisCI

### PR DESCRIPTION
**Pull request by huminzhi**

### CODE REVIEW

**Comment by huminzhi** [comment]
This can fix one of the unit test issues

**Comment by kchitalia** [comment]
LGTM

**Comment by bhariharan** [comment]
@huminzhi How does this fix a test? The other two headers are public headers too, correct?

**Comment by huminzhi** [comment]
right @bhariharan , it's something really weird and likely an xcode bug, according to @wmathurin we had similar issue before: 
https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/1338
And from what I tried, it does fix the compiling issue on TravisCI (it's likely fixed in xcode7.3, however, on travisCI, we have to use xcode7.2 for another reason...) looking forward to move out of TravisCI...

**Pull request closed without merging**
