### PR TITLE
Removed more orphan references

### PR DESCRIPTION
**Pull request by AsceticMonk**
**Changes**
- Removed more orphan references in projects
- Enabled `Parallelize Build` option for several targets

### CODE REVIEW

**Review by trooper2013 — APPROVED** [review]
@AsceticMonk We should test these changes with building the hybrid sdk. I think there was a reason why we had not made this change. Could have been due to static libs in the past. Nevertheless its worth checking.

**Review by bhariharan — APPROVED** [review]
Historically, we've had issues with parallelization in the hybrid projects, but maybe they don't exist anymore.

**Comment by AsceticMonk** [comment]
@bhariharan @trooper2013 Any way I can check for the concern you stated?

**Comment by bhariharan** [comment]
@AsceticMonk Update the submodule for this repo and pull in the latest `dev` branch into the hybrid repo [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Hybrid) on the `dev` branch, and try building the frameworks and running the sample apps.

**Comment by AsceticMonk** [comment]
@bhariharan Thanks! I did the verification just now. Pointed the submodule to `dev` in the hybrid project, and I was still able to build and run AccountEditor without any issue.

**Pull request merged**
