### PR TITLE
Long queries should be allowed

### PR DESCRIPTION
**Pull request by bhariharan**
The query length is not limited to ```1024``` anymore.

### CODE REVIEW

**Comment by wmathurin** [comment]
A new test maybe (could be in SalesforceRestAPITests - a soql query with  a select ... in very long)?

**Comment by bhariharan** [comment]
I'll try to come up with a long query.

**Comment by bhariharan** [comment]
@wmathurin Added a test [here](https://github.com/bhariharan/SalesforceMobileSDK-iOS/commit/229153e229e5320f2e31f28e39c890691902f29e).

**Comment by wmathurin** [comment]
:+1:

**Pull request merged**
