### PR TITLE
Adding remote ghost records sync API

### PR DESCRIPTION
**Pull request by bhariharan**
Only outstanding item is adding tests.

### CODE REVIEW

**Comment by bhariharan** [comment]
The implementation follows the same design as the ```Android``` side.

**Comment by kchitalia** [comment]
One question, do we need to somehow show this functionality in the sample app?

**Comment by bhariharan** [comment]
Not at this time. It's a simple API call. I'll be adding doc for the new API.

**Comment by kchitalia** [comment]
Sounds good :+1:

**Comment by bhariharan** [comment]
Added tests in latest commit.

**Pull request merged**
