### PR TITLE
Removing unnecessary linker flag

### PR DESCRIPTION
**Pull request by bhariharan**

### CODE REVIEW

**Comment by bhariharan** [comment]
@khawkins This appears to be unnecessary after you removed ```SqliteAdditions```. Sample apps appear to run fine.

**Comment by khawkins** [comment]
Should we just remove the flag?  Default value is `NO`.

**Comment by bhariharan** [comment]
Sure - I could do that. I did a search-and-replace ;-)

**Comment by bhariharan** [comment]
@khawkins Done [here](https://github.com/bhariharan/SalesforceMobileSDK-iOS/commit/be644925930f4d3f3b5d58fd39577228d2c99c74).

**Comment by bhariharan** [comment]
@jeanbovet FYI - you shouldn't need this flag anymore.

**Comment by khawkins** [comment]
:+1:

**Comment by wmathurin** [comment]
I also took it out of the template pod file here:
https://github.com/forcedotcom/SalesforceMobileSDK-iOS/commit/04fea434be7c15bb07914f48932068015ac42bb4

(I meant to do a pull request, but due to a user error, I pushed to forcedotcom directly :-(

**Comment by jeanbovet** [comment]
:+1:

**Pull request merged**
