### PR TITLE
Moving to SQLCipher 4.5.0

### PR DESCRIPTION
**Pull request by wmathurin**
Like on Android (see https://github.com/forcedotcom/SalesforceMobileSDK-Android/pull/2265), had to tweak tests doing explain query plan.

NB, they are two failures I need to look into:
* testUpgradeNoSaltLegacyKey
* testUpgradeLegacySaltLegacyKey

### CODE REVIEW

**Review by bhariharan — APPROVED** [review]

**Comment by wmathurin** [comment]
The two tests failures happen with SQLCipher 4.5.0 but not with 4.4.3. Looking into them.

**Comment by wmathurin** [comment]
Here is what I found out for the failing tests.

When we unlock the database we do the following to automatically migrate settings if dealing with a SQLCipher 2.x or 3.x database:
```objective-c
[[db executeQuery:@"PRAGMA cipher_migrate"] close];
```
We never checked the result set to see whether the migration was successful. 
It turns out, it returns an error (non zero integer) in those tests that change encryption. It can be seen by using the following code instead:
```objective-c
FMResultSet* res = [db executeQuery:@"PRAGMA cipher_migrate"];
if ([res next]) {
  int migrationResult = [res intForColumnIndex:0];
  if (migrationResult != 0) {
  // migration failed
  [SFSDKSmartStoreLogger e:[self class] format:@"Error running cipher_migrate for store '%@'", [db databasePath]];
  }
}
[res close];
```
It is happening with both SQLCipher 4.5.0 and 4.4.3.
In SQLCipher 4.5.0, however, `PRAGMA cipher_migrate` causes the database to permanently enter an error state if a migration fails (see [release notes](https://www.zetetic.net/blog/2021/10/28/sqlcipher-4.5.0-release/). That's why the tests are now failing.

Since it's a 4.x database, I'm not sure why cipher_migrate is complaining.
Considering that we started using 4.x in 7.1, this call would only be useful for customer attempting to jump from Mobile SDK 7.0 to 10.0. I'm not even sure that's possible given the deprecated code we have removed.

I recommend we drop that call to cipher_migrate. Thoughts? @bhariharan @bbirman

**Comment by bbirman** [comment]
@wmathurin sounds good to me

**Review by bbirman — APPROVED** [review]

**Comment by bhariharan** [comment]
Sounds good to me as well.

**Pull request merged**
