### PR TITLE
Removing SalesforceKit

### PR DESCRIPTION
**Pull request by bhariharan**
The internal jobs need to be updated to point to the new home. Not ready for merging until then.

### CODE REVIEW

**Comment by kchitalia** [comment]
I'll have to do the work for adding in the resource bundle in the Foundation SDK repo, ya?

**Comment by bhariharan** [comment]
@kchitalia No. Stay tuned - I'll email you the info :-)

**Comment by kchitalia** [comment]
Sounds good.

**Comment by bhariharan** [comment]
Build scripts have been updated to the new repo and it's working as expected. This is ready to merge.

**Pull request merged**
