### PR TITLE
apply ios13 default pagesheet for login host list view

### PR DESCRIPTION
**Pull request by TLiu2121999**
Reverting change https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/3052

We are ready to apply ios13 default modal view presentation style to pagesheet

### CODE REVIEW

**Comment by TLiu2121999** [comment]
@wmathurin

**Comment by wmathurin** [comment]
@trooper2013 @bhariharan Do we want to change the default behavior?

**Comment by TLiu2121999** [comment]
@wmathurin Just want to be clear, this change is the default behavior. The previous pr https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/3052 was actually overwriting the default behavior. @bhariharan

**Comment by wmathurin** [comment]
iOS 13 changed the way it renders UIModalPresentationPageSheet. They appear as a card (not full screen) that can be dismissed with a swipe. The previous pr https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/3052 was meant to keep the UX the same. 
Are we ready to change the user experience? Is it okay if the user can swipe the screen away?

**Comment by bhariharan** [comment]
@wmathurin Thanks for explaining. In that case, I don't think we should put this in. The screen should not be swipeable.

**Comment by TLiu2121999** [comment]
ok, but just FYI, we are changing all other modal pages on Salesforce App to the default pageSheet, I've confirmed with our PM, she thinks it's ok to make this page swipe-able; But if msdk feel strongly about this, we are ok with either way. @bbirman @wmathurin

**Comment by bhariharan** [comment]
I think non-swipeable would be my preferred option, but I'll leave it up to @wmathurin and @trooper2013 to decide.

**Comment by TLiu2121999** [comment]
@wmathurin @trooper2013 what's the final decision here?

**Comment by wmathurin** [comment]
(Let me 180 - I was too quick on my earlier review), I think it's fine for the **host list screen** to be swipe-able.

**Pull request merged**
