### PR TITLE
alterSoup with soup spec for hybrid / react native

### PR DESCRIPTION
**Pull request by wmathurin**
running new hybrid tests (for register with spec and alter with spec)
latest shared

### CODE REVIEW

**Comment by bhariharan** [comment]
👍

**Comment by khawkins** [comment]
:+1:

**Comment by wmathurin** [comment]
Do not merge yet - the richer alter soup with spec tests (brought in with
With https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/1683/commits/eff3ed85ff3e4876dfa2af7e1b706708cf83f575) are not passing - I need to investigate

**Comment by wmathurin** [comment]
With https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/1683/commits/3998946f0ff50a0c4a560b66df2c05b58fbdc373 all the hybrid smartstore tests are passing

**Pull request merged**
