### PR TITLE
Add SFApplicationHelper.h to public headers in podspec.

### PR DESCRIPTION
**Pull request by kchitalia**

### CODE REVIEW

**Comment by rgoldiez** [comment]
@kchitalia - I pulled in this fix and got past my original issue, but running an issue with this file now (perhaps it's also relatively new)?

#import <SalesforceSDKCore/SFSDKLoginHost.h>

**Comment by kchitalia** [comment]
@rgoldiez I'm sorry, which file?

**Comment by bhariharan** [comment]
:+1:

**Comment by wmathurin** [comment]
Looks like SFSDKLoginHost.h also need to be made public in the podspec.

**Comment by rgoldiez** [comment]
This one too... i'm working thru the podspec also.

```
#import <SalesforceSDKCore/SFSDKLoginHostDelegate.h>
```

**Comment by kchitalia** [comment]
@wmathurin I thought we had added all the login host related headers to the podspec.

**Comment by kchitalia** [comment]
Check this out: https://github.com/forcedotcom/SalesforceMobileSDK-iOS/commit/b196de6effde6306b900ee4bfdd66f1a3ebbbf30

**Comment by bhariharan** [comment]
@kchitalia That commit adds it only to the static target, not the podspec.

**Comment by wmathurin** [comment]
That makes them public in the xcode project. Cocoapod relies exclusively on the podspec, so whatever is made public in the xcode project needs to also be made public in the podspec.
We have a script that keeps both in sync for all our libraries except for SalesforceSDK, where we need to do it manually.

**Comment by rgoldiez** [comment]
Good news... I updated my podspec with the all of the LoginHost references and I'm able to build again... and I can now hide the login navbar.  I sincerely appreciate all the help.

**Comment by kchitalia** [comment]
@wmathurin Ah, I see what you mean.

**Pull request merged**
