### PR TITLE
Removing UIWebView support

### PR DESCRIPTION
**Pull request by bhariharan**

### CODE REVIEW

**Comment by bhariharan** [comment]
Hybrid apps `AccountEditor` and `SmartSyncExplorerHybrid` are working fine.

**Comment by robbmcmahan** [comment]
@bhariharan we have a UIWebview fallback plan and need to keep that capability

**Comment by bhariharan** [comment]
@robbmcmahan That'll need to be implemented in the subclass in `S1`. With ATS restrictions coming, Apple's official stance is deprecation of `UIWebView` and ATS won't work there, so we won't be supporting it officially either.

**Comment by bhariharan** [comment]
@robbmcmahan Also, the right hooks are available for `S1` to implement `UIWebViewDelegate` in a subclass.

**Comment by wmathurin** [comment]
:+1:

**Comment by robbmcmahan** [comment]
@bhariharan what about needing to pass the engine we are going to use to MSDK? Can we still pass the UIWebView engine?

**Comment by bhariharan** [comment]
@robbmcmahan That API still exists [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/1748/files#diff-bafe72208f1ff3afa7b2024a36312efeL198).

**Comment by robbmcmahan** [comment]
ok, so this doesn't stop us from passing in the UI engine and using our own UIWebView. Gotcha

**Comment by khawkins** [comment]
Looks fine to me.  There are some failing hybrid tests, but I'm not sure if it's related.

**Comment by bhariharan** [comment]
All tests are passing, except a few in `SmartSyncPlugin`. Seems unrelated to this PR.

**Pull request merged**
