### PR TITLE
Removing openssl from dependencies

### PR DESCRIPTION
**Pull request by wmathurin**

### CODE REVIEW

**Comment by wmathurin** [comment]
Problems I mentioned in the scrum update (run time crashes) went away after resetting simulator / cleaning up DerivedData.

**Comment by wmathurin** [comment]
Next (and final) stop: cordova plugin repo config / update.sh script

**Comment by bhariharan** [comment]
:+1: 

Do we need to make any updates to the ```podspec```?

**Comment by khawkins** [comment]
:+1: 

Yeah, podspec dependencies should come out too.

**Comment by wmathurin** [comment]
True.

**Comment by wmathurin** [comment]
Pod spec update: https://github.com/wmathurin/SalesforceMobileSDK-iOS/commit/d7092e5f8823efe334563f8844c3194a4df50c35

**Comment by bhariharan** [comment]
:+1:

**Pull request merged**
