### PR TITLE
Custom view SmartSyncExplorer for IDP - (Commented out by default)

### PR DESCRIPTION
**Pull request by trooper2013**
Adding custom view to SmartSyncExplorer sample for enabling IDP login flow - (Commented out by default). Easy enough to uncomment and try out.

### CODE REVIEW

**Comment by brandonpage** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Code coverage under minimum of 55%</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Needs testing on a Phone if change is non-trivial</td>
    </tr>
  </tbody>
</table>

## Current coverage for SalesforceAnalytics.framework is `42.86%`
✅ *No files affecting coverage found*

---
## Current coverage for SalesforceSDKCore.framework is `25.41%`
✅ *No files affecting coverage found*

---
## Current coverage for SmartStore.framework is `38.33%`
✅ *No files affecting coverage found*

---
## Current coverage for SmartSync.framework is `78.76%`
✅ *No files affecting coverage found*

---

> Powered by [xcov](https://github.com/nakiostudio/xcov)

<p align="right" data-meta="generated_by_CI-result">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by trooper2013** [comment]
@wmathurin This is sample code. It should reside in the sample. Demonstrates how to customize the Login flow Selection view.

**Comment by wmathurin** [comment]
I know. But it is like our passcode screen, it doesn't look great, we don't expect customers to ship app with it, but at least they can start using right away.
If the code lives in the sample app only, it's not available when you generate an app with forceios, you have to clone the main repo etc. If it was in SalesforceSDKCore, they could use right away.

**Comment by wmathurin** [comment]
Could you put the block of commented out code in the template maybe?

**Pull request merged**
