### PR TITLE
Remove appending of current UA

### PR DESCRIPTION
**Pull request by bhariharan**

### CODE REVIEW

**Comment by bhariharan** [comment]
We never did append the current UA on ```Android```. This brings parity.

**Comment by kchitalia** [comment]
👍

**Comment by wmathurin** [comment]
Is this going to throw off some server side logic?

**Comment by bhariharan** [comment]
It shouldn't. It's a legacy component. The server side logic has changed to check the values in our UA format to determine if it's coming from `mobile`.

**Pull request merged**
