### PR TITLE
update readme to use the test results from github

### PR DESCRIPTION
**Pull request by helenren**
remove the build configure file for travis ci.

### CODE REVIEW

**Comment by helenren** [comment]
@huminzhi

**Comment by huminzhi** [comment]
👍 Thank you @helenren !

**Comment by bhariharan** [comment]
@helenren Could you rebase against `unstable` please? There seem to be a bunch of merge commits. Otherwise looks good.

**Comment by helenren** [comment]
sure, will do. Thanks

**Comment by helenren** [comment]
I will close this one to rebase my repo code, then open a new one.

**Pull request closed without merging**
