### PR TITLE
Rolling SalesforceNetwork and SalesforceRestAPI into SalesforceSDKCore

### PR DESCRIPTION
**Pull request by bhariharan**
- Updated pod specs.
- Updated project references and schemes.
- Removed all references to `SalesforceNetwork` and `SalesforceRestAPI`.
- All tests passing.
- Sample apps are working (native and hybrid).

### CODE REVIEW

**Comment by khawkins** [comment]
I'll take your word for it. ;-)

**Comment by wmathurin** [comment]
Are the tests combined under one test target in SalesforceSDKCore, or did you keep different test targets?

**Comment by bhariharan** [comment]
I put the tests under `SalesforceSDKCore` as well for consistency.

**Comment by wmathurin** [comment]
👍

**Comment by jeffreyjackson** [comment]
So we don't need SalesforceRestAPI pod anymore, it's just under SalesforceSDKCore pod now?

**Comment by bhariharan** [comment]
@jeffreyjackson You won't need them from our next release.

**Pull request merged**
