### PR TITLE
Removing frameworks

### PR DESCRIPTION
**Pull request by bhariharan**

### CODE REVIEW

**Comment by bhariharan** [comment]
@khawkins Might need your expertise reviewing this (if it is reviewable at all, that is).

**Comment by wmathurin** [comment]
Looks fine

**Comment by khawkins** [comment]
Looking at it now.

**Comment by khawkins** [comment]
[This block](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/981/files#diff-4a2ffb07a7c50ec79dc2c25e2db06763R75) needs to go.

**Comment by khawkins** [comment]
[These two blocks](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/981/files#diff-4a2ffb07a7c50ec79dc2c25e2db06763R103) need to go.

**Comment by khawkins** [comment]
[These two lines](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/981/files#diff-4a2ffb07a7c50ec79dc2c25e2db06763R229) need to go.

**Comment by khawkins** [comment]
[These two lines](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/981/files#diff-4a2ffb07a7c50ec79dc2c25e2db06763R240) also need to go.

**Comment by khawkins** [comment]
[These two blocks](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/981/files#diff-4a2ffb07a7c50ec79dc2c25e2db06763R532) should go.

**Pull request merged**
