### PR TITLE
check nullability before adding to dictionary

### PR DESCRIPTION
**Pull request by liguopku**
@bhariharan @sgoldberg-sfdc
we run into an crash when account is null
Screen Shot 2020-11-05 at 2 55 01 PM

### CODE REVIEW

**Comment by bhariharan** [comment]
@liguopku I'm not sure this is the right fix. If control comes to `completeWithSuccess`, the value of `account` should never be `nil`. How do you reproduce this? It seems to indicate an underlying issue. What do you think, @trooper2013?

**Comment by trooper2013** [comment]
> @liguopku I'm not sure this is the right fix. If control comes to `completeWithSuccess`, the value of `account` should never be `nil`. How do you reproduce this? It seems to indicate an underlying issue. What do you think, @trooper2013?

I have seen this issue prop up in the past too. We should find out why the userAccount is nil. Adding a check may prevent a crash but it's not the right solution. Why would a userAccount not be found during the refresh? There could be an issue with the lookup of the user account, in which case we should find out why (maybe community handling related)?  Is it possible that a logout is in progress?

**Comment by liguopku** [comment]
@bhariharan @trooper2013 Thanks for the feedback! I have put the cause of the logout and refresh flow into an internal quip document and we can discuss the details there. For long term goals, we will turn off refresh on 403 from the app by default. If certain cases where refresh is required, app side need to handle them by itself.

**Comment by bhariharan** [comment]
@liguopku There are 3 issues here:

- Refresh token expires immediately.
- API access is disabled for the user, which causes a `403` response.
- Auto-refresh on `403`.

Since we don't refresh on `403` anymore, this situation should not arise going forward. We will independently augment our code to ensure that refresh flow doesn't occur when logout is in progress. I'm going to close this for now, based on an internal discussion @trooper2013, @bbirman, and I had.

**Pull request closed without merging**
