### PR TITLE
fix cordova issue when achiving app

### PR DESCRIPTION
**Pull request by liguopku**
@bbirman @khawkins @sgoldberg-sfdc 

http://stackoverflow.com/questions/34546607/xcode-7-2-in-archive-getting-the-issue-cordova-cdvviewcontroller-h-file-n

After adding the search path I can archive scheme 'SalesforceHybridSDKStatic'.We will need to cherrypick this one back to our repo later

### CODE REVIEW

**Comment by huminzhi** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          2 Errors
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Tests have failed, see below for more information.</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Code coverage under minimum of 80%</td>
    </tr>
  </tbody>
</table>

### Tests: 

Classname | Name|
--- | ---|
SmartSyncTestSuite | testCleanResyncGhosts|
SmartSyncTestSuite | testFetchApexRestObjectsFromServer|
SmartSyncTestSuite | testFetchSObjects|
SmartSyncTestSuite | testFetchSObjectsFromServer|
SmartSyncTestSuite | testRefreshSyncDown|
SmartSyncTestSuite | testReSync|
SmartSyncTestSuite | testSObjectCollectionFetch|
SmartSyncTestSuite | testSObjectDestroy|
SmartSyncTestSuite | testSObjectFetch|
SmartSyncTestSuite | testSObjectSave|
SmartSyncTestSuite | testSyncApexRestObjectWithServerCreate|
SmartSyncTestSuite | testSyncApexRestObjectWithServerDelete|
SmartSyncTestSuite | testSyncApexRestObjectWithServerRead|
SmartSyncTestSuite | testSyncApexRestObjectWithServerUpdate|
SmartSyncTestSuite | testSyncDown|
SmartSyncTestSuite | testSyncDownToGlobalStore|
SmartSyncTestSuite | testSyncDownToGlobalStoreNamed|
SmartSyncTestSuite | testSyncDownWithNoOverwrite|
SmartSyncTestSuite | testSyncSObjectCreate|
SmartSyncTestSuite | testSyncSObjectDelete|
SmartSyncTestSuite | testSyncSObjectDetectConflictCreate|
SmartSyncTestSuite | testSyncSObjectDetectConflictDelete|
SmartSyncTestSuite | testSyncSObjectDetectConflictRetrieve|
SmartSyncTestSuite | testSyncSObjectDetectConflictUpdate|
SmartSyncTestSuite | testSyncSObjectRetrieve|
SmartSyncTestSuite | testSyncSObjectUpdate|
SmartSyncTestSuite | testSyncSObjectWithServerCreate|
SmartSyncTestSuite | testSyncSObjectWithServerDelete|
SmartSyncTestSuite | testSyncSObjectWithServerRead|
SmartSyncTestSuite | testSyncSObjectWithServerUpdate|
SmartSyncTestSuite | testSyncUpLocallyDeleted|
SmartSyncTestSuite | testSyncUpLocallyDeletedWithNoOverwrite|
SmartSyncTestSuite | testSyncUpLocallyUpdated|
SmartSyncTestSuite | testSyncUpLocallyUpdatedWithGlobalStore|
SmartSyncTestSuite | testSyncUpLocallyUpdatedWithGlobalStoreNamed|
SmartSyncTestSuite | testSyncUpLocallyUpdatedWithNoOverwrite|


## Current coverage for SalesforceHybridSDK.framework is `31%`
✅ *No files affecting coverage found*

---
## Current coverage for SalesforceAnalytics.framework is `41%`
✅ *No files affecting coverage found*

---
## Current coverage for SalesforceSDKCore.framework is `19%`
✅ *No files affecting coverage found*

---
## Current coverage for SmartStore.framework is `23%`
✅ *No files affecting coverage found*

---
## Current coverage for SmartSync.framework is `1%`
✅ *No files affecting coverage found*

---

> Powered by [xcov](https://github.com/nakiostudio/xcov)

<p align="right" data-meta="generated_by_CI-result">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by liguopku** [comment]
@bhariharan Thanks for the review! I add the UninstalledProducts to the xcconfig files.

**Comment by bhariharan** [comment]
@liguopku According to [this](http://stackoverflow.com/questions/34546607/xcode-7-2-in-archive-getting-the-issue-cordova-cdvviewcontroller-h-file-n) post, this is fixed in `Cordova 3.9.2`, which is the version we use. Why do we still need this?

**Comment by liguopku** [comment]
@bbirman hmm I am on dev branch and cordova is set to 4.3.0 according to this commit.
https://github.com/forcedotcom/SalesforceMobileSDK-iOS/commit/d7c827c0d17b92f5576cdfb9aa21bfd0f65facec

And cordova has a regression issue reported by other people in version 4.3.0. [Here](https://cordova.apache.org/announcements/2016/10/24/ios-release.html) is the post.

I can reproduce the issue locally.
screen shot 2017-04-14 at 3 35 45 pm

**Comment by bhariharan** [comment]
@liguopku This change is breaking all our hybrid tests and we're really close to our release. I don't think we can accept this change at this time.

**Comment by liguopku** [comment]
Oh sure. This is not something urgent. I will close this one and try it again later.

**Pull request closed without merging**
