### PR TITLE
Taking the broken completion block hack out of SFRootViewManager

### PR DESCRIPTION
**Pull request by khawkins**
This fixes the issues we were seeing in iOS 8.3 apps.  Cc: @tpesce

### CODE REVIEW

**Comment by bhariharan** [comment]
:+1: 

@khawkins Part of this needs to go into ```master``` for a patch release. Would you like me to backport to ```master``` or do you want to submit a pull request for that?

**Comment by khawkins** [comment]
I'll PR for master too.

**Comment by bhariharan** [comment]
Thanks! :+1:

**Comment by khawkins** [comment]
Rebased onto the master -> unstable change.  Should be good to go here.

**Comment by tpesce** [comment]
Thank you! :+1:

**Pull request merged**
