### PR TITLE
Make projects in workspace Xcode 11.0 compatible

### PR DESCRIPTION
**Pull request by bhariharan**
A checkbox in `Xcode`.

### CODE REVIEW

**Comment by bhariharan** [comment]
I don't think so - this is just the project file format (which hasn't changed). Could you run it on `Xcode 10.3` locally and check? I overwrote it with `Xcode 11` :-(

**Comment by wmathurin** [comment]
XCode 10.3 won't open the projects anymore.

Screen Shot 2019-09-23 at 11 02 53 AM

**Comment by bhariharan** [comment]
@wmathurin Do we care? In the past, we've always required the latest version of `Xcode` with the major version. Besides, you need it for `iOS 13` anyway. Keeps the test matrix easier.

**Comment by wmathurin** [comment]
Waiting to see if Xcode 11 Circle CI will add 12.4 simulators. Otherwise, we need to go back and lower deployment target to 12.2 everywhere.

**Comment by bhariharan** [comment]
Closing this for now, until `Xcode 11` adds a `iOS 12.4` simulator.

**Pull request closed without merging**
