### PR TITLE
Having the os restriction here means that we need to use a different …

### PR DESCRIPTION
**Pull request by wmathurin**
…package.json for iOS react native template and Android react native template

So the only place where we will have the os = darwin constraint is in the package.json for forceios

### CODE REVIEW

**Comment by helenren** [comment]
👍

**Comment by bhariharan** [comment]
Maybe we don't need that explicit constraint for `forceios` - why would any developer attempt to run `forceios` on `win`? :-) We could add a note in the doc instead, if that's easier.

**Comment by wmathurin** [comment]
forceios and forcedroid are the only ones users will actually npm install manually - all the other package.json are only used when pulling in dependencies.
I think it makes sense to prevent forceios installation on non mac os machines since it cannot possibly work. Beside we have had the {os:darwin} in the forceios package.json since day one.
It  ended up in the other ones because, I copied the package.json from forceios over and overloooked the {os:darwin} entry.

**Comment by bhariharan** [comment]
Sounds good!  👍

**Pull request merged**
