### PR TITLE
Adding support for 'Remember User Name'

### PR DESCRIPTION
**Pull request by bhariharan**

### CODE REVIEW

**Comment by kchitalia** [comment]
1. Do we already have unit tests for this?
2. Is this a bug we are fixing?

**Comment by bhariharan** [comment]
This is in the ```WebView``` - there's no way to add unit tests for it. It's not a bug fix - it's an enhancement on the login page, owned by the auth team.

**Comment by khawkins** [comment]
Seems fine, albeit with slight reservations about `removeAllCookies` retaining its naming convention, now that it no longer does. :)  Are there any scenarios where we might still want to be able to clear the entire state, including the user?

**Comment by bhariharan** [comment]
I can't think of any use case. On ```Android```, we have the ability to do that explicitly with a ```Clear Cookies``` button in the menu, but we've never had that on ```iOS```.

**Comment by kchitalia** [comment]
I tried the SmartSyncExplorerHybrid Sample App without this change. I checked the "Remember me" checkbox. I logged in to the App, then I logged out. The next time I try to login to the same login host, it remembers my user name. 

How will the app behave after this change?

**Comment by bhariharan** [comment]
This is not for that flow. This is for the verification code on pre-approved device flow. Once a device is approved, you won't need to type in the verification code again if it has been whitelisted once.

**Comment by kchitalia** [comment]
Ah. Got it.

**Pull request merged**
