### PR TITLE
use domain for token endpoint

### PR DESCRIPTION
**Pull request by huminzhi**
FYI @khawkins @bhariharan 
In regards to Kevin's comment

### CODE REVIEW

**Comment by khawkins** [comment]
[Related](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/1646/files/ec1c094083cd237be32c8cf205cfcf4c4b616f21#r74953149) (for posterity).

**Comment by khawkins** [comment]
LGTM.

**Comment by kchitalia** [comment]
:+1:

**Comment by bhariharan** [comment]
👍

**Pull request merged**
