### PR TITLE
Init cursorCache to prevent getting nil cursor

### PR DESCRIPTION
**Pull request by booker0108**
Fixing the problem of inserting cursor to a nil object
No failure on inserting cursor to a nil object but lead to failure when trying to  manipulate cursor afterwards

### CODE REVIEW

**Comment by wmathurin** [comment]
Why do we need this? Move cursor method calls cursor by id which creates the cursor cache map if needed.

**Comment by booker0108** [comment]
I have a problem resulting in app crash with React Native if you don't init the cursorCache

1. smartstore.querySoup
2. smartstore.moveCursorToNextPage
 Then it crashed

**Comment by huminzhi** [comment]
## Danger has errored
[!] Invalid `DangerFile` file: `minimum_coverage_percentage` value must be a Float! Found Integer instead.
```
 #  from DangerFile:5
 #  -------------------------------------------
 #  
 >  xcov.report(
 #     scheme: 'UnitTests',
 #  -------------------------------------------
```

<p align="right" data-meta="generated_by_CI-result">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by booker-laputa** [comment]
Will this be merged?

**Comment by booker0108** [comment]
Will this pull request merge?

**Comment by wmathurin** [comment]
Thanks @booker0108 !

**Pull request merged**
